# Basics
title: Mauricio's homepage
description: Mauricio's Personal Portfolio

# GitHub Pages URL settings
url: "https://<your-username>.github.io"  # change to your username
baseurl: ""                               # for project sites use "/repo-name"

theme: jekyll-theme-slate
